##
## Gets all sub directories which match the passed regex.
##
function(Sf_GetSubDirectories VarOut Directory MatchStr)
	file(GLOB _Children RELATIVE "${Directory}" "${Directory}/*")
	set(_List "")
	foreach (_Child ${_Children})
		if (IS_DIRECTORY "${Directory}/${_Child}")
			if ("${_Child}" MATCHES "${MatchStr}")
				list(APPEND _List "${_Child}")
			endif ()
		endif ()
	endforeach ()
	set(${VarOut} ${_List} PARENT_SCOPE)
endfunction()

function(Sf_GetQtVersionDirectory _VarOut)
	set(_QtDir "")
	if (NOT "${CMAKE_HOST_SYSTEM_NAME}" STREQUAL "${CMAKE_SYSTEM_NAME}" AND "${CMAKE_HOST_SYSTEM_NAME}" STREQUAL "Linux")
		set(_QtDir "$ENV{HOME}/lib/QtWin")
	elseif ("${CMAKE_SYSTEM_NAME}" STREQUAL "Linux")
		set(_QtDir "$ENV{HOME}/lib/Qt")
	elseif ("${CMAKE_SYSTEM_NAME}" STREQUAL "Windows")
		set(_QtDir "")
		# Iterate through all the most logical drives. (Drive P is preferred so put in front.)
		set(_Drives P C D E F G H I J K L M N O P Q R S T U V W X Y Z)
		foreach (_Drive ${_Drives})
			if (EXISTS "${_Drive}:/Qt/")
				set(_QtDir "${_Drive}:/Qt")
				message(STATUS "Qt root library found in '${_QtDir}'!")
				break()
			endif ()
		endforeach ()
	endif ()
	Sf_GetSubDirectories(_SubDirs "${_QtDir}" "^[0-9]+\\.[0-9]+\\.[0-9]+$")
	list(LENGTH _SubDirs _Len)
	if (NOT ${_Len})
		message(STATUS "Qt versioned library not found in '${_QtDir}'!")
		set(${_VarOut} "" PARENT_SCOPE)
		return()
	endif ()
	list(SORT _SubDirs COMPARE NATURAL ORDER DESCENDING)
	list(GET _SubDirs 0 _QtVerDir)
	set(${_VarOut} "${_QtDir}/${_QtVerDir}" PARENT_SCOPE)
endfunction()

# Set the Qt Library location variable.
if (NOT DEFINED QT_DIRECTORY)
	Sf_GetQtVersionDirectory(QT_DIRECTORY)
	if (QT_DIRECTORY STREQUAL "")
		# When not found define it as empty.
		set(QT_DIRECTORY "")
	else()
		message(STATUS "Qt Version Directory: ${QT_DIRECTORY}")
		# When changing this CMAKE_PREFIX_PATH remove the 'cmake-build-xxxx' directory
		# since it weirdly keeps the previous selected CMAKE_PREFIX_PATH
		if (WIN32)
			if (CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
				set(QT_LIBS_SUBDIRECTORY "msvc2019_64")
			else ()
				set(QT_LIBS_SUBDIRECTORY "mingw_64")
			endif ()
			message(STATUS "Qt Libraries: ${QT_LIBS_SUBDIRECTORY}")
			list(PREPEND CMAKE_PREFIX_PATH "${QT_DIRECTORY}/${QT_LIBS_SUBDIRECTORY}")
			set(QT_INCLUDE_DIRECTORY "${QT_DIRECTORY}/${QT_LIBS_SUBDIRECTORY}/include")
		else ()
			list(PREPEND CMAKE_PREFIX_PATH "${QT_DIRECTORY}/gcc_64")
			set(QT_INCLUDE_DIRECTORY "${QT_DIRECTORY}/gcc_64/include")
		endif ()
	endif()
endif ()
